# -*- coding: utf-8 -*-
"""
Created on Thu Sep  9 10:20:52 2021

@author: talha
"""


#libaries
import tensorflow as tf

#seed
seed = 42 

#contains original images 

original_image_path = "../2-Data/"

import os 

#check directory is exist
if isinstance(original_image_path, str): #Image path is a string 
    if os.path.exists(original_image_path):
        print ("Path is exist")
    else:
        raise FileNotFoundError('Image is not found on your system')    


#contains the image which is generated by image generator 
processed_image_path ="../4-Dataset_Class/datagenerator_augmented_image"
if isinstance(processed_image_path, str): #Image path is a string 
    if os.path.exists(processed_image_path):
        print ("Path is exist")
    else:
        raise FileNotFoundError('datagenerator_augmented_image is not found on your system')   
        
        
data_augmentation = tf.keras.Sequential([
     tf.keras.layers.experimental.preprocessing.RandomFlip("horizontal_and_vertical"),
     tf.keras.layers.experimental.preprocessing.RandomRotation(0.2)])

#list the image_name
imgs_name = os.listdir(original_image_path+"original_images") #Read the image name inside the path
img_array = []        


# CV2 IMREAD  
import cv2
original_images = []
for img in imgs_name:    
    original_images.append(cv2.cvtColor(cv2.imread(os.path.join(original_image_path+"original_images", img)),cv2.COLOR_BGR2RGB)) 
 
    
import sys
sys.path.append('../3-Utils/')
from visualize_data import visualize_keras

for i in range(len(original_images)):
    image = tf.expand_dims(original_images[i], 0)   
    augmented_images = data_augmentation(image)
    visualize_keras(original_images[i],augmented_images[0])
    

